apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gohacker-data
  namespace: gohacker
  labels:
    app: gohacker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
